/* Context uses packaged aggregates only. No map state, network request or new selector. */
(()=>{'use strict';
 const D=window.ACU_R74_CONTEXT_DATA,esc=ACU_R72.escape;
 const num=x=>Number(x).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1});
 const fmt=(x,r)=>x==null?'Sem dado':num(x)+(r.family==='ideb'?'':r.family==='access'?' km':'%');
 const source=id=>D.sources.find(s=>s.source_id===id);
 const all=c=>[...c.records,...c.supplementary,...c.ideb,...c.access];
 const ids=rows=>[...new Set(rows.flatMap(r=>Object.values(r.evidence).map(e=>e.source_id)))];
 function sourcesFor(rows){const used=new Set();return ids(rows).map(source).filter(s=>s&&!used.has(s.official_url)&&used.add(s.official_url)).map(s=>'<a href="'+esc(s.official_url)+'" target="_blank" rel="noopener">'+esc(s.institution+' · '+s.title)+'</a>').join(' · ');}
 function methodology(cityId){const c=D.cities[cityId];return '<details class="r73-methodology"><summary>Fonte e metodologia do contexto municipal</summary>'+ids(all(c)).map(id=>{const s=source(id);return '<p><strong>'+esc(s.title)+':</strong> '+esc(s.formula)+' '+esc(s.universe)+' '+esc(s.methodological_limitations)+'</p>';}).join('')+'<p>'+sourcesFor(all(c))+'</p><p><a href="governance/context_r74/CONTEXT_SOURCE_REGISTRY.json" target="_blank">Registro das fontes</a> · <a href="governance/context_r74/CONTEXT_DICTIONARY.json" target="_blank">Dicionário</a> · <a href="governance/context_r74/CONTEXT_AGGREGATE_TABLE.csv">Tabela agregada</a></p></details>';}
 function table(c,rows,caption,local=false){const levels=local?[['municipality',c.name]]:[['municipality',c.name],['state',c.state],['brazil','Brasil']];return '<table><caption>'+esc(caption)+'</caption><thead><tr><th>Indicador</th>'+levels.map(x=>'<th>'+esc(x[1])+'</th>').join('')+'<th>Ano</th></tr></thead><tbody>'+rows.map(r=>'<tr data-context-indicator="'+esc(r.indicator_id)+'"><td>'+esc(r.title)+(r.family==='ideb'?'<small class="r74-row-meta">Rede '+esc(r.network.toLowerCase())+' · urbana · índice 0–10</small>':'')+'</td>'+levels.map(([key,label])=>'<td data-label="'+esc(label)+'" data-context-level="'+key+'">'+(r.availability?.[key]==='INCOMPATIBLE_UNIVERSE'?'<span class="r74-missing" title="Universo nacional urbano e rural, diferente do recorte urbano municipal e estadual">Recorte distinto¹</span>':fmt(r.values[key],r))+'</td>').join('')+'<td data-label="Ano">'+esc(String(r.year))+'</td></tr>').join('')+'</tbody></table>'+(rows.length?'<p class="r73-context-source">'+sourcesFor(rows)+'</p>':'');}
 function education(c,indicator){const relevant=/distor|age.grade/i.test(indicator||'')?'distortion':'abandonment';const primary=c.records.filter(r=>r.stage==='EF').sort((a,b)=>Number(b.family===relevant)-Number(a.family===relevant));
  return '<div data-context-family="education"><h3>Educação · comparação municipal</h3>'+table(c,c.ideb.filter(r=>r.primary),'Ideb 2025 · ensino fundamental regular · índice de 0 a 10')+'<p class="r74-note">¹ Nos anos iniciais, a rede pública nacional inclui escolas urbanas e rurais; município e UF usam o recorte urbano. Esse valor nacional fica fora da comparação.</p><details><summary>Anos iniciais · comparação da rede estadual</summary>'+table(c,c.ideb.filter(r=>!r.primary),'Recorte próprio: rede estadual urbana nos três níveis · índice de 0 a 10')+'</details>'+table(c,primary,'Trajetória escolar 2024 · todas as redes e localizações · ensino regular · %')+'<details><summary>Trajetória escolar · outras etapas</summary>'+table(c,c.records.filter(r=>r.stage!=='EF'),'2024 · todas as redes e localizações · ensino regular · %')+'</details></div>';
 }
 function wash(c){if(!c.supplementary.length)return '';return '<div data-context-family="wash"><h3>WASH nas escolas · 2025</h3><p>Escolas estaduais e municipais ativas. Percentuais de matrículas, com universo diferente dos indicadores domiciliares.</p>'+table(c,c.supplementary,'Contexto local · matrículas da educação básica · %',true)+'<details><summary>Definições e denominadores escolares</summary>'+c.supplementary.map(r=>'<p><strong>'+esc(r.title)+':</strong> '+esc(r.definition)+' '+esc(String(r.numerator))+' / '+esc(String(r.denominator))+' matrículas. '+esc(r.limitations)+'</p>').join('')+'</details></div>';}
 function access(c){if(!c.access.length)return '';return '<div data-context-family="access"><h3>Dispersão e afastamento geométrico</h3>'+table(c,c.access,'Contexto local · distâncias em linha reta · km',true)+'<p class="r74-note">O P90 ordena distâncias das localidades elegíveis à sede; a unidade observada é a localidade. Não mede percurso, tempo ou acesso de crianças à escola.</p><details><summary>Universos e períodos das distâncias</summary>'+c.access.map(r=>'<p><strong>'+esc(r.title)+':</strong> '+esc(r.definition)+' '+esc(r.period)+'.</p>').join('')+'<p>Cadastro municipal: '+esc(String(c.access[0].localities_total))+' localidades. A saída não individualiza o N elegível do cálculo. Distância zero ao nó regional é um valor geométrico da matriz; não comprova oferta de serviços. Sem comparadores validados para a UF inteira ou Brasil.</p></details></div>';}
 function render(cityId,geography,theme,indicator){const c=D.cities[cityId];if(!c)return '';const isWash=theme==='R71_HOUSEHOLDS'||/agua|water|sewer|wash|sanit/i.test(indicator||'');const edu=education(c,indicator),w=wash(c),a=access(c);return '<section class="r73-context r74-context" data-city="'+cityId+'"><h2>Contexto do município · '+esc(c.name)+'</h2><p>Município completo. A seleção “'+esc(geography.name)+'” não altera a geografia destes valores.</p>'+(isWash&&w?w+'<details><summary>Educação · Ideb e trajetória escolar</summary>'+edu+'</details>':edu+(w?'<details><summary>WASH nas escolas</summary>'+w+'</details>':''))+(a?'<details><summary>Dispersão e afastamento geométrico</summary>'+a+'</details>':'')+'<details><summary>Como interpretar e cobertura</summary><p>Diferenças de Ideb em pontos do índice; diferenças de taxas em pontos percentuais. Comparações descritivas entre recortes compatíveis, sem teste de significância. O ano aparece em cada linha. Abandono não é evasão; resultados municipais não representam o território prioritário.</p><p>PNDS: pesquisa identificada; a cobertura e o produto recente permanecem em verificação documental. <a href="'+D.pnds.methodology+'" target="_blank">Identificação e produtos examinados</a>.</p></details>'+methodology(cityId)+'</section>';}
 function answer(cityId,question){const q=String(question||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(!/ideb|abandono|distor|contexto municipal|wash escolar|agua.*escola|escola.*agua|saneamento.*escola|pnds|distancia|dispersao|acesso|p90/.test(q))return null;const c=D.cities[cityId];
  if(/pnds/.test(q))return {html:'<h2>PNDS · pesquisa identificada</h2><p>'+esc(c.pending[0])+'</p><p><a href="'+D.pnds.methodology+'" target="_blank">Documentação oficial e cobertura examinada</a></p>',claims:[],source_ids:[],city:cityId};
  let rows;
  if(/ideb/.test(q)){rows=c.ideb.filter(r=>q.includes('estadual')?r.network==='Estadual':r.primary);if(/anos iniciais/.test(q))rows=rows.filter(r=>r.stage==='AI');if(/anos finais/.test(q))rows=rows.filter(r=>r.stage==='AF');}
  else if(/distancia|dispersao|acesso|p90/.test(q)){rows=c.access;if(/p90/.test(q))rows=rows.filter(r=>r.indicator_id==='R74_FA_D1');}
  else if(/wash escolar|agua.*escola|escola.*agua|saneamento.*escola/.test(q))rows=c.supplementary;
  else {rows=c.records.filter(r=>(!q.includes('abandono')||r.family==='abandonment')&&(!q.includes('distor')||r.family==='distortion'));const stage=/anos iniciais/.test(q)?'AI':/anos finais/.test(q)?'AF':/ensino medio/.test(q)?'EM':'EF';rows=rows.filter(r=>r.stage===stage);}
  const claims=[];let html='<h2>Contexto do município · '+esc(c.name)+'</h2><p>Município completo; não representa o bairro, setor, AP ou território prioritário selecionado.</p>';
  for(const r of rows){html+='<p><strong>'+esc(r.title)+' ('+esc(String(r.year))+'):</strong> '+fmt(r.values.municipality,r)+'. '+esc(r.family==='ideb'?'Índice 0–10 · rede '+r.network.toLowerCase()+' · urbana.':r.family==='access'?r.definition:r.universe);
   for(const [k,label] of [['state',c.state],['brazil','Brasil']])if(r.values[k]!=null&&r.values.municipality!=null&&r.comparison_allowed?.[k]!==false){const diff=Math.round((r.values.municipality-r.values[k])*10)/10;html+=' '+esc(label)+': '+fmt(r.values[k],r)+'; diferença município − '+esc(label)+': '+num(diff)+(r.family==='ideb'?' pontos do índice.':' p.p.');}
   if(r.excluded_comparators?.brazil)html+=' Brasil excluído desta comparação por universo urbano/rural distinto.';
   if(r.family==='access')html+=' '+esc(r.limitations);
   html+='</p>';claims.push({indicator_id:r.indicator_id,year:r.year,unit:r.unit,network:r.network,geography:c.ibge7,values:r.values,evidence:r.evidence});
  }
  if(!rows.length)html+='<p>Sem resultado validado desta combinação para '+esc(c.name)+'.</p>';
  html+='<p class="r73-context-source">'+sourcesFor(rows)+'</p><p>Comparação descritiva; sem inferência causal, teste de significância ou precisão não estimada.</p>';
  return {html,claims,source_ids:ids(rows),city:cityId};
 }
 window.ACU_R74_CONTEXT={render,answer,methodology,data:city=>D.cities[city]};
 window.ACU_R73_CONTEXT=window.ACU_R74_CONTEXT; // Existing application contract retained.
})();
