/* R77: one SP register, shared map/directory/comparison/context; no network calls. */
window.ACU_R77=(()=>{
 'use strict';
 const D=window.ACU_R77_DATA,$=s=>document.querySelector(s),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fold=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const byId=new Map(D.units.map(u=>[u.id,u])),sourceIndex=new Map(D.sources.map(s=>[s.source_id,s]));
 const types={CRAS:'CRAS',CREAS:'CREAS',DDM:'DDM',CENTRO_CASA:'Centros e casas',POSTO:'Postos avançados',COMUNITARIA:'Iniciativas comunitárias',JURIDICO:'Apoio jurídico'};
 const children={CONFIRMED:'Atendimento infantil/adolescente confirmado',NOT_SERVED:'Não atende, conforme documentação',UNCONFIRMED:'Público infantil/adolescente não confirmado'};
 const locations={VALIDATED:'Localização validada',ADDRESS_PENDING:'Localização a confirmar',ADDRESS_DIVERGENT:'Endereço a confirmar',NO_PUBLIC_ADDRESS:'Endereço público não identificado',NO_FIXED_SITE:'Sem sede fixa',OUTSIDE_MUNICIPALITY:'Fora do município'};
 const state={type:'',nature:'',child:'',scope:'city',query:'',unmapped:false,city:null};let bridge=null,map=null,layer=null,groups=[],lastPack=null,lastPanorama=null,catalogRefresh=null,pendingOpen=false;
 const active=city=>city==='sao_paulo';
 const metric=id=>String(id).startsWith('R77_NETWORK_');
 const sources=(ids,compact=false)=>[...new Set(ids)].map(id=>{const s=sourceIndex.get(id);return s?`<a href="${E(s.official_url)}" target="_blank" rel="noopener noreferrer">${E(compact?s.institution:s.title)}</a>${compact?'':` <small>(${E(s.reference_period)})</small>`}`:'';}).filter(Boolean).join(' · ');
 function selected(){return bridge?.state.geographyId||'SP_MUNICIPALITY';}
 function relevant(u){const gid=selected();return state.scope==='city'||gid==='SP_MUNICIPALITY'||u.territory_ids.includes(gid)||u.reference_district_ids.includes(gid);}
 function filtered(){if(!active(bridge?.state.cityId))return [];return D.units.filter(u=>relevant(u)&&(!state.type||u.type===state.type)&&(!state.nature||u.nature===state.nature)&&(!state.child||u.child_status===state.child)&&(!state.query||fold(u.name+' '+u.address).includes(fold(state.query)))&&(!state.unmapped||!u.map_eligible));}

 const CATEGORY='R77_NETWORK';
 const enabled=()=>active(bridge?.state.cityId)&&bridge?.state.layerState.equipment===true;
 function categoryValues(s=bridge?.state){return [...new Set((s?.data?.equipment||[]).map(i=>i.category).filter(Boolean))].sort().concat(CATEGORY);}
 function selection(s=bridge?.state){const f=s?.equipmentFilters||{};return Array.isArray(f.categories)?f.categories:f.category?[f.category]:null;}
 function categorySelected(item,s=bridge?.state){const c=selection(s);return c===null||c.includes(item.category)||(item.r77_network&&c.includes(CATEGORY));}
 function equipmentMatch(item,s){if(!active(s.cityId))return null;if(!categorySelected(item,s))return false;return !item.r77_unit_ids?.length||item.r77_unit_ids.some(id=>filtered().some(u=>u.id===id));}
 function mapEquipmentEligible(item,s){if(!active(s.cityId))return true;const c=selection(s);if(c===null||c.includes(item.category))return true;return Boolean(c.includes(CATEGORY)&&item.r77_unit_ids?.some(id=>byId.get(id)?.map_eligible));}
 function mapUnits(){if(!active(bridge?.state.cityId))return [];const f=bridge.state.equipmentFilters,items=new Map(bridge.state.data.equipment.map(e=>[e.id,e]));return filtered().filter(u=>{const e=items.get(u.equipment_id);return u.map_eligible&&e&&categorySelected(e)&&(!f.subcategory||e.subcategory===f.subcategory)&&(!f.status||(e.operational_status||e.status)===f.status)&&(!f.governmentLevel||e.government_level===f.governmentLevel);});}
 function renderedIds(){return new Set((enabled()?mapUnits():[]).map(u=>u.equipment_id));}
 function visibleUnits(){return bridge?.state.module==='panorama'&&enabled()&&map?._loaded?mapUnits().filter(u=>map.getBounds().contains([u.latitude,u.longitude])):[];}
 function countText(){return `${D.summary.directory} registros no cadastro · ${D.summary.location.VALIDATED} unidades localizadas. ${visibleUnits().length} unidades visíveis no enquadramento; ${mapUnits().length} elegíveis nos filtros da camada. ${filtered().length} registros na consulta do diretório.`;}
 function controls(s,mode='map'){
  if(!active(s.cityId))return '';const cats=categoryValues(s),selected=selection(s),chosen=c=>selected===null||selected.includes(c),label=c=>bridge?.categoryLabel?.(c)||c.replaceAll('_',' ');
  const categoryCheck=c=>`<label class="r77-category-choice"><input type="checkbox" data-equipment-category-choice="${E(c)}" ${chosen(c)?'checked':''}> ${E(c===CATEGORY?'Rede de proteção e apoio à mulher':label(c))}</label>`;
  return `<div class="r77-equipment-selection" data-mode="${mode}"><label><input type="checkbox" data-equipment-category-all ${selected===null||cats.every(chosen)?'checked':''}> Todas as categorias</label>${categoryCheck(CATEGORY)}<details id="r77-category-detail"><summary>Filtros e diretório da rede</summary><div class="r77-filters"><label>Tipo de serviço<select id="r77-type"><option value="">Todos os serviços</option>${Object.entries(types).map(([v,t])=>`<option value="${v}" ${state.type===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Natureza<select id="r77-nature"><option value="">Pública e comunitária</option><option value="PUBLICA" ${state.nature==='PUBLICA'?'selected':''}>Pública / serviço da rede pública</option><option value="COMUNITARIA" ${state.nature==='COMUNITARIA'?'selected':''}>Sociedade civil</option></select></label><label>Público<select id="r77-child"><option value="">Todos os estados de confirmação</option>${Object.entries(children).map(([v,t])=>`<option value="${v}" ${state.child===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Recorte da rede<select id="r77-scope"><option value="city" ${state.scope==='city'?'selected':''}>Município inteiro</option><option value="context" ${state.scope==='context'?'selected':''}>Território selecionado e referências</option></select></label></div><button type="button" id="r77-directory">Consultar diretório</button><p id="r77-count" aria-live="polite">${E(countText())}</p><details class="r77-coverage"><summary>Fontes e cobertura do cadastro parcial</summary><p>72 registros somente em lista: 57 localizações a confirmar, 10 endereços divergentes, 2 sem sede fixa e 3 sem endereço público. Os 67 pendentes são os dois primeiros grupos.</p><p>Camada desligada ou filtros sem pontos não significam ausência de atendimento. O diretório permanece disponível. Categorias podem compartilhar unidades; cada identidade é exibida uma vez.</p><p>C: CRAS · E: CREAS · D: DDM · ✚: centros/casas · P: postos · ◇: iniciativas. Números agrupam unidades próximas.</p><p>Referências de atendimento não são instalações locais nem áreas oficiais de abrangência. O nome da rede não torna todos os serviços exclusivos de mulheres ou de menores.</p><small>Fonte: ${sources(['SRC_ACU_R77_SP_NETWORK'],true)} · conferência 07/10/2026. ${D.summary.countable_units} unidades identificadas entre ${D.summary.directory} registros de consulta; os demais são canais e referências.</small></details></details><details class="r77-other-categories"><summary>Outras categorias de equipamentos</summary>${cats.filter(c=>c!==CATEGORY).map(categoryCheck).join('')}</details></div>`;
 }
 function updateCount(){if($('#r77-count'))$('#r77-count').textContent=countText();}
 function syncControls(){const s=bridge?.state;if(!s)return;const chosen=selection(s);document.querySelectorAll('[data-equipment-category-choice]').forEach(i=>i.checked=chosen===null||chosen.includes(i.dataset.equipmentCategoryChoice));document.querySelectorAll('[data-equipment-category-all]').forEach(i=>{i.checked=chosen===null||categoryValues(s).every(c=>chosen.includes(c));i.indeterminate=chosen!==null&&chosen.length>0&&!i.checked;});document.querySelectorAll('[data-map-layer="equipment"]').forEach(i=>i.checked=s.layerState.equipment);}
 function update(){syncControls();if(bridge?.state.module==='panorama')bridge.refresh();else if(bridge?.state.module==='equipment')catalogRefresh?.();updateCount();}
 function bindControls(){for(const key of ['type','nature','child','scope'])$('#r77-'+key)?.addEventListener('change',e=>{state[key]=e.target.value;update();});$('#r77-directory')?.addEventListener('click',()=>directory());
  document.querySelectorAll('[data-equipment-category-choice]').forEach(i=>i.onchange=()=>{const s=bridge.state,cats=new Set(selection(s)||categoryValues(s));i.checked?cats.add(i.dataset.equipmentCategoryChoice):cats.delete(i.dataset.equipmentCategoryChoice);s.equipmentFilters.categories=[...cats];s.equipmentFilters.category='';if(i.checked)s.layerState.equipment=true;update();});
  document.querySelectorAll('[data-equipment-category-all]').forEach(i=>i.onchange=()=>{bridge.state.equipmentFilters.categories=i.checked?null:[];bridge.state.equipmentFilters.category='';if(i.checked)bridge.state.layerState.equipment=true;update();});syncControls();
 }
 function mapStatus(){if(!active(bridge?.state.cityId)||!enabled())return '';const ids=new Set([...(bridge.state.markerRecords||[]).filter(r=>r.kind==='equipment').map(r=>r.id),...renderedIds()]);return `${ids.size} equipamentos com localização após filtros (união de identificadores); ${mapUnits().length} unidades operacionais da rede representadas. Cadastro parcial.`;}
 function openCategory(){pendingOpen=true;const s=bridge.state;s.layerState.equipment=true;const cats=selection(s);if(cats&&!cats.includes(CATEGORY))s.equipmentFilters.categories=[...cats,CATEGORY];if(lastPanorama)Object.assign(s,lastPanorama);else Object.assign(s,{theme:'Demografia e adolescentes',indicatorId:'demo_population_total_n',mapIndicator:'demo_population_total_n'});bridge.panorama();}
 function installEquipmentSection(){const group=$('[data-r77-equipment-group]'),panel=$('.map-control-panel-compact');if(!group||!panel||group.parentElement.dataset.mapControlSection==='equipment')return;const section=document.createElement('section');section.className='map-control-section r77-equipment-section';section.dataset.mapControlSection='equipment';section.hidden=bridge.state.mapControlSection!=='equipment';section.append(group);panel.querySelector('#map-layer-status').before(section);group.open=true;}
 function reveal(){if(!pendingOpen)return;const tools=$('.r71-map-tools'),group=$('[data-r77-equipment-group]');if(tools&&group){tools.open=true;bridge.equipmentSection();group.open=true;pendingOpen=false;}}
 function connect(b){bridge=b;const s=b.state;if(state.city===s.cityId)return;state.city=s.cityId;state.type=state.nature=state.child=state.query='';state.scope='city';state.unmapped=false;lastPack=null;lastPanorama=null;catalogRefresh=null;pendingOpen=active(s.cityId)&&new URLSearchParams(location.hash.slice(1)).get('equipmentTools')==='1';discard();if(active(s.cityId)&&new URLSearchParams(location.hash.slice(1)).get('network')==='1'){s.layerState.equipment=true;pendingOpen=true;}}

 function openDialog(title,html){const dialog=$('#detail-dialog');$('#detail-title').textContent=title;$('#detail-content').innerHTML=html;if(!dialog.open)dialog.showModal();}
 function rowButton(u){return `<article class="r77-directory-row"><button type="button" data-r77-unit="${E(u.id)}">${E(u.name)}</button><span>${E(types[u.type])} · ${E(locations[u.location_status])}</span>${!u.unit_count_eligible?'<small>Canal ou referência; fora da contagem de unidades.</small>':''}${state.scope==='context'&&!u.territory_ids.includes(selected())&&u.reference_district_ids.includes(selected())?'<small>Referência de atendimento; não é instalação comprovada neste território.</small>':''}</article>`;}
 function bindUnits(){document.querySelectorAll('[data-r77-unit]').forEach(b=>b.onclick=()=>detail(b.dataset.r77Unit));}
 function directory(onlyIds=null){
  openDialog('Rede de proteção e apoio à mulher — diretório',`<div class="r77-directory"><p>Registros com ponto, canais e endereços a confirmar. Cadastro parcial; confirme as condições no canal institucional.</p><div class="r77-directory-tools"><input id="r77-search" type="search" aria-label="Buscar na rede" placeholder="Nome ou endereço" value="${E(state.query)}"><label><input id="r77-unmapped" type="checkbox" ${state.unmapped?'checked':''}> Somente sem ponto</label></div><p id="r77-directory-count"></p><div id="r77-directory-rows"></div></div>`);
  const draw=()=>{const rows=onlyIds?onlyIds.map(id=>byId.get(id)).filter(Boolean):filtered();$('#r77-directory-count').textContent=`${rows.length} registros · ${rows.filter(u=>u.map_eligible).length} com ponto`;$('#r77-directory-rows').innerHTML=rows.map(rowButton).join('')||'<p>Nenhum registro identificado com estes filtros. Isso não demonstra ausência de atendimento.</p>';bindUnits();};
  $('#r77-search').oninput=e=>{state.query=e.target.value;draw();update();};$('#r77-unmapped').onchange=e=>{state.unmapped=e.target.checked;draw();update();};draw();
 }
 function detail(id){const u=byId.get(id);if(!u)return;const physical=u.district_id?bridge?.state.data.geographies.find(g=>g.id===u.district_id)?.name:null;const refs=u.reference_district_ids.map(gid=>bridge?.state.data.geographies.find(g=>g.id===gid)?.name).filter(Boolean);
  openDialog('Rede de proteção e apoio à mulher',`<article class="r77-unit" data-r77-detail="${E(id)}"><button type="button" id="r77-back">← Diretório</button><h2>${E(u.name)}</h2><p class="r77-kind">${E(types[u.type])} · ${u.nature==='PUBLICA'?'Rede pública':'Sociedade civil'}</p><p><strong>${E(children[u.child_status])}</strong><br>${E(u.child_description)}</p><p>${E(u.address||locations[u.location_status])}<br><span class="r77-location">${E(locations[u.location_status])}${physical?' · Distrito '+E(physical):''}</span></p>${u.phone?`<p><strong>Contato institucional:</strong> ${E(u.phone)}</p>`:''}${u.email?`<p><a href="mailto:${E(u.email)}">${E(u.email)}</a></p>`:''}${u.hours?`<p><strong>Horário informado:</strong> ${E(u.hours)}<br><small>${sources([u.hours_source_id],true)}</small></p>`:''}<p><a href="${E(u.site)}" target="_blank" rel="noopener noreferrer">Consultar canal da instituição / fonte</a></p><footer>Fonte: ${sources([u.source_id],true)} · conferência 07/10/2026. Funcionamento não verificado presencialmente.</footer><details><summary>Fonte e metodologia</summary><p>${E(u.description)}</p><p><strong>Localização:</strong> ${u.map_eligible?'Coordenada do acervo oficial R76-R1, conferida pelo logradouro e número e pelos limites municipais. Precisão posicional não publicada.':'Sem coordenada elegível; registro excluído das contagens espaciais e das distâncias.'}</p>${u.location_source_ids.length?`<p>Fonte da localização: ${sources(u.location_source_ids)}</p>`:''}<p><strong>Organização:</strong> ${E(u.organization_name||"Não confirmada")}</p><p><strong>Público:</strong> ${u.child_source_ids.length?sources(u.child_source_ids):'Evidência específica ainda não disponível.'}</p>${refs.length?`<p>Referências editoriais de atendimento: ${E(refs.join(', '))}. Não são áreas de abrangência, exclusividade ou prova de proximidade.</p>`:''}<p>${u.unit_count_eligible?'Unidade operacional identificada; sua inclusão no mapa exige localização validada.':'Canal ou referência sem identidade/local de unidade operacional suficientemente confirmado; não conta como unidade.'}</p><p>Homologação institucional não documentada. Cadastro parcial; não mede capacidade, demanda atendida ou acesso efetivo.</p><p>${sources(u.source_ids)}</p><dl>${Object.entries(u.field_sources).map(([key,ids])=>`<dt>${E(({name:"Nome",type:"Tipo",address:"Endereço",phone:"Telefone",email:"E-mail",hours:"Horário",nature:"Natureza",description:"Atendimento",child_status:"Público infantil",location:"Localização"})[key]||key)}</dt><dd>${sources(Array.isArray(ids)?ids:[ids],true)}</dd>`).join("")}</dl></details></article>`);
  $('#r77-back').onclick=()=>directory();
 }
 function discard(){if(layer){layer.remove();layer=null;}if(map){map.off('zoomend',rebuild);map.off('moveend',updateCount);}map=null;groups=[];}
 function rebuild(){if(!map||!map._loaded)return;layer?.remove();groups=[];if(!enabled()){updateCount();return;}
  const buckets=new Map();for(const u of mapUnits()){const p=map.project([u.latitude,u.longitude],map.getZoom()),key=Math.floor(p.x/24)+':'+Math.floor(p.y/24);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(u);}
  const markers=[];for(const us of buckets.values()){const u=us[0],symbol=us.length>1?String(us.length):({CRAS:'C',CREAS:'E',DDM:'D',CENTRO_CASA:'✚',POSTO:'P',COMUNITARIA:'◇',JURIDICO:'J'}[u.type]);const label=us.length>1?us.length+' unidades próximas: '+us.map(x=>x.name).join('; '):u.name+' · '+types[u.type];const marker=L.marker([u.latitude,u.longitude],{icon:L.divIcon({className:'r77-marker',html:`<span aria-hidden="true">${E(symbol)}</span>`,iconSize:[22,22],iconAnchor:[11,11]}),keyboard:true,autoPanOnFocus:false,riseOnHover:true,title:label});marker.bindTooltip(E(label),{direction:'top',className:'r77-tooltip'});marker.on('click',e=>{if(e.originalEvent)L.DomEvent.stopPropagation(e.originalEvent);us.length>1?directory(us.map(x=>x.id)):detail(u.id);});marker.on('add',()=>{const el=marker.getElement();if(el){el.setAttribute('aria-label',label);el.dataset.r77Units=us.map(x=>x.id).join('|');}});markers.push(marker);groups.push(us.map(x=>x.id));}
  layer=L.layerGroup(markers).addTo(map);bridge.state.markerLayers.r77_network=layer;updateCount();
 }
 function mapLayer(s){if(map!==s.map){discard();if(s.map&&active(s.cityId)){map=s.map;map.on('zoomend',rebuild);map.on('moveend',updateCount);}}if(!active(s.cityId)){discard();return;}rebuild();setTimeout(reveal,1500);}
 function pack(s,geo){if(!active(s.cityId))return null;const gid=geo?.id||s.geographyId;const a=D.aggregates.find(x=>x.geography_id===gid&&x.type==='TOTAL');if(!a)return null;const rows=a.unit_ids.map(id=>byId.get(id)),ids=[...new Set(['SRC_ACU_R77_SP_NETWORK',...rows.flatMap(u=>u.source_ids)])];if(ids.some(id=>!sourceIndex.has(id)))return null;return {contract:'R77_NETWORK_CONTEXT',city_id:'sao_paulo',geography_id:gid,source_ids:ids,lineage_id:'LIN_R77_SP_NETWORK',unit_ids:a.unit_ids,claims:{located_units:a.located_unit_count,types:[...new Set(rows.map(u=>types[u.type]))],confirmed_child_units:rows.filter(u=>u.child_status==='CONFIRMED').length,municipal_directory:D.summary.directory,municipal_located:D.summary.location.VALIDATED},limitations:'Cadastro parcial; localizações pendentes não são atribuídas ao território. Referências não são instalações. Não mede demanda, cobertura assistencial ou causalidade.'};}
 function summary(s,geo){const p=pack(s,geo);if(!p)return '';lastPack=p;const c=p.claims,name=geo?.display_name||geo?.name||s.data.geographies.find(g=>g.id===p.geography_id)?.name||'São Paulo';return `<article id="r77-assistant-summary" class="r77-context" data-city="sao_paulo"><h3>Rede cadastrada · ${E(name)}</h3><p>${c.located_units?`${c.located_units} unidades com localização validada neste recorte: ${E(c.types.join(', '))}.`:'Nenhuma unidade identificada com localização validada neste recorte do cadastro parcial.'} ${c.confirmed_child_units} têm atendimento infantil/adolescente documentado; as modalidades e restrições constam nas fichas.</p><p>No município, ${c.municipal_located} de ${c.municipal_directory} registros do diretório têm ponto validado. Registros pendentes não são atribuídos a este território. Isso não demonstra ausência nem suficiência de atendimento.</p><small>${sources(['SRC_ACU_R77_SP_NETWORK'],true)} · conferência 07/10/2026. Universos da rede e da população são distintos.</small></article>`;}
 function afterRender(b){connect(b);const s=b.state;if(!active(s.cityId))return;
  if(s.module==='panorama'&&[...document.querySelectorAll('#theme-select option')].some(o=>o.value===s.theme))lastPanorama={theme:s.theme,indicatorId:s.indicatorId,mapIndicator:s.mapIndicator};
  if(['panorama','equipment'].includes(s.module)){if(s.module==='panorama')installEquipmentSection();bindControls();if(s.module==='panorama')setTimeout(reveal,1500);}
  if(s.module==='violence'){$('#module-view .r50-diagnostic-intro')?.insertAdjacentHTML('beforeend','<button type="button" id="r77-open-map" class="quiet-button">Rede de proteção e apoio à mulher em Equipamentos</button>');$('#r77-open-map')?.addEventListener('click',openCategory);}
  if(s.module==='assistant')$('#module-view').insertAdjacentHTML('afterbegin',summary(s,b.geo()));
  if(s.module==='sources')$('#module-view').insertAdjacentHTML('afterbegin',`<details class="r77-context"><summary>Rede de proteção e apoio à mulher — São Paulo</summary><p>Cadastro parcial conciliado na R77, sem atualização de dados nesta revisão. ${D.summary.location.VALIDATED} localizações validadas. As referências por distrito não são instalações. As contagens são de unidades operacionais e as distâncias partem de um ponto interno geométrico.</p><p>${sources(['SRC_ACU_R77_SP_NETWORK','MURAL_REDE','PMSP_CASAS_NORTE','SMADS_CRAS_ZONA_NORTE','PCSP_DDM'])}</p><span>Relatório interno de auditoria não integra esta revisão pública.</span> · <span>Relatório interno de auditoria não integra esta revisão pública.</span></details>`);
 }
 function append(s){if(!active(s.cityId))return;const h=summary(s,bridge?.geo());$('#assistant-output')?.insertAdjacentHTML('beforeend',h.replace('id="r77-assistant-summary"','data-r77-assistant-result="true"'));}
 function answer(s,q){if(!active(s.cityId)||!/rede|cras|creas|apoio|delegacia|protecao/.test(fold(q))||/belem|manaus|sao luis|rio de janeiro/.test(fold(q)))return null;const html=summary(s,bridge?.geo()).replace('id="r77-assistant-summary"','data-r77-assistant-answer="true"');return html?{html,pack:lastPack,intent:'R77_NETWORK_CONTEXT'}:null;}
 function equipmentDetail(row){const ids=row.r77_unit_ids;if(row.map_eligible&&ids?.length&&!ids.some(id=>byId.get(id)?.map_eligible))return false;if(!active(bridge?.state.cityId)||!ids?.length)return false;ids.length===1?detail(ids[0]):directory(ids);return true;}
 function reset(){state.type=state.nature=state.child=state.query='';state.unmapped=false;state.scope='city';update();}
 return {active,metric,connect,afterRender,mapLayer,append,answer,equipmentDetail,summary,pack,sources,reset,enabled,controls,openCategory,equipmentMatch,mapEquipmentEligible,renderedIds,mapStatus,setCatalogRefresh:fn=>{catalogRefresh=fn;},snapshot:()=>({city:state.city,enabled:enabled(),categories:selection(),filters:{...state},map_units:groups.flat().length,marker_groups:groups,network_equipment_ids:[...renderedIds()],visible_units:visibleUnits().length,directory:filtered().length,evidence:lastPack}),detail,directory};
})();
