/* R71 joins household presentation to the existing Panorama selectors. */
(()=>{'use strict';
 window.R71PatternCanvas=L.Canvas.extend({_fillStroke(ctx,l){
  if(!l.options.r71Missing)return L.Canvas.prototype._fillStroke.call(this,ctx,l);
  const kind=l.options.r75MissingKind||'missing';this._r75Patterns??={};
  if(!this._r75Patterns[kind]){
   const t=document.createElement('canvas');t.width=t.height=10;const q=t.getContext('2d');
   q.fillStyle='rgba(247,248,249,0.75)';q.fillRect(0,0,10,10);q.strokeStyle='rgba(82,97,108,0.65)';q.fillStyle=q.strokeStyle;q.lineWidth=1;
   if(kind==='suppressed'){q.beginPath();q.moveTo(0,10);q.lineTo(10,0);q.moveTo(0,0);q.lineTo(10,10);q.stroke();}
   else {q.beginPath();q.arc(3,3,1,0,Math.PI*2);q.fill();}
   this._r75Patterns[kind]=ctx.createPattern(t,'repeat');
  }
  ctx.save();ctx.globalAlpha=1;ctx.fillStyle=this._r75Patterns[kind];ctx.fill(l.options.fillRule||'evenodd');ctx.restore();
  const fill=l.options.fill;l.options.fill=false;L.Canvas.prototype._fillStroke.call(this,ctx,l);l.options.fill=fill;
 }});
 const C=R68Core,H=R71Colors,cfg=ACU_R70_CONFIG,F=C.fmt;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let active=null,pendingLegacy=false,lastScope=null;const cache={};
 function script(src,key){if(window[key])return Promise.resolve(window[key]);return new Promise((resolve,reject)=>{const e=document.createElement('script');e.src=src;e.onload=()=>ACU_R79_ASSETS.ready(key).then(resolve,reject);e.onerror=()=>reject(Error('Não foi possível ler '+src));document.body.append(e);});}
 function load(city){return cache[city]??=city==='belem'?Promise.all([script('cities/belem/households_r69/data.js','ACU_R69_DATA'),script('cities/belem/households_r69/geometry.js','ACU_R69_GEOMETRY')]):Promise.all([script('cities/'+city+'/households_r70/data.js','ACU_R70_DATA_'+city),script('cities/'+city+'/households_r70/geometry.js','ACU_R70_GEOMETRY_'+city)]);}
 function prepare(context){
  if(context.theme!=='R71_HOUSEHOLDS')return Promise.resolve(null);
  return load(context.cityId).catch(e=>{delete cache[context.cityId];throw e;});
 }
 function stop(){active?.destroy();}
 function mount(context){
  if(active?.map===context.map)return active.update(context);
  stop();const map=context.map,city=context.cityId;let isHousing=context.theme==='R71_HOUSEHOLDS',themeId=String(context.indicator||'').replace('housing:',''),scale=themeId==='joint'?'ap':'setor',theme=cfg.themes[themeId];
  const grid=document.querySelector('.cartography-grid'),panel=grid.querySelector('.map-panel'),aside=grid.querySelector('aside'),legend=document.querySelector('#map-legend');
  document.body.classList.add('r71-panorama');document.body.classList.toggle('r71-housing',isHousing);
  const bar=document.createElement('div');bar.className='r71-statusbar';bar.innerHTML='<div><strong id="r71-measure"></strong><small id="r71-coverage"></small></div><div class="r71-actions"><button id="r71-find" type="button">'+(isHousing?'Buscar unidade':'Território em números')+'</button><button id="r71-about" type="button">Sobre o indicador</button></div>';grid.before(bar);
  const tools=document.createElement('details');tools.className='r71-map-tools';tools.innerHTML='<summary>Camadas e filtros</summary>';const baseControls=panel.querySelector('.map-control-panel');baseControls.before(tools);tools.append(baseControls);const periodControls=document.getElementById('violence-context-slot');if(periodControls)tools.append(periodControls);
  const close=document.createElement('button');close.className='r71-sheet-close';close.type='button';close.setAttribute('aria-label','Fechar ficha');close.textContent='Fechar ×';aside.prepend(close);
  const sheet=document.createElement('section');sheet.className='r71-household-sheet';sheet.hidden=!isHousing;sheet.innerHTML='<label>Buscar setor ou AP<input id="r71-search" type="search" autocomplete="off" placeholder="Código ou nome da unidade"></label><div id="r71-searchResults"></div><div id="r71-detail"></div>';aside.prepend(sheet);aside.prepend(close);
  const dialog=document.createElement('dialog');dialog.className='r71-about';dialog.innerHTML='<form method="dialog"><h2>Sobre o indicador</h2><button aria-label="Fechar">×</button></form><div class="r71-about-body"></div>';document.body.append(dialog);
  let D=null,G=null,source={},units=[],byId={},geometries={},layer=null,polygons=new Map(),selected=null,disposed=false,ready=!isHousing,scope=null,inScope=new Set();
  const $=id=>document.getElementById('r71-'+id),status=s=>cfg.status_labels[s]||D?.status_labels[s]||s;
  const sourceLink=id=>source[id]?'<a href="'+esc(source[id].url)+'" target="_blank" rel="noopener">'+esc(source[id].institution+' — '+source[id].title)+'</a>':esc(id);
  const resize=()=>{if(!disposed)requestAnimationFrame(()=>{if(!disposed)context.resizeMap();});};
  function openSheet(){grid.classList.add('r71-sheet-open');resize();}
  function closeSheet(){selected=null;grid.classList.remove('r71-sheet-open');layer?.setStyle(f=>style(byId[f.properties.id]));resize();map.r72Labels?.schedule();}
  close.onclick=closeSheet;
  $('find').onclick=()=>{openSheet();if(isHousing){detail();$('search').focus();}};
  function legacy(){if(isHousing)return;legend.querySelectorAll('.legend-row').forEach(row=>{if(row.querySelector('span')?.textContent.trim()==='N/D'){row.querySelector('i').style.background='repeating-linear-gradient(135deg,#fff 0 5px,#718694 5px 6px,#fff 6px 9px)';row.querySelector('span').textContent='N/D · ausente/suprimido';}});const select=document.querySelector('#indicator-select'),label=select.selectedOptions[0]?.textContent||'Indicador territorial';$('measure').textContent=label;$('coverage').textContent='Recorte selecionado: '+((context.getGeography?.()||context.geography).name||context.geography.id)+' · fonte, medida e cobertura na legenda e na ficha.';const geo=context.getGeography?.()||context.geography;if(context.audit?.map_enabled)$('coverage').textContent=(map._r73Clip?'Base do indicador: ':'')+context.audit.available_units+'/'+context.audit.total_units+' unidades territoriais com valor · '+geo.name+'. Fonte e medida na legenda e na ficha.';if((geo.level==='MUNICIPALITY'||geo.id==='BELEM_CITY_CONTEXT')&&window['ACU_R71_COVERAGE_'+city]?._meta.municipal_display_bounds){document.getElementById('r71-coverage').textContent+=' Enquadramento urbano; cobertura municipal por unidades territoriais.';}if(map._r73Clip)$('coverage').textContent+=' '+ACU_R73_DISPLAY.notice(map,'native');}
  if(!isHousing){legacy();$('about').onclick=context.openMethod;if(pendingLegacy){openSheet();pendingLegacy=false;}}
  else{$('measure').textContent='Carregando indicador…';legend.hidden=true;}
  const coverageData=window['ACU_R71_COVERAGE_'+city];let urbanFrame=context.geography.level==='MUNICIPALITY'||context.geography.id==='BELEM_CITY_CONTEXT'?coverageData?._meta.municipal_display_bounds:null;
  const legacyOriginal=legacy;
  function destroy(){if(disposed)return;if(map._animatingZoom&&map._mapPane)map._onZoomTransitionEnd();map.stop();disposed=true;if(layer){map.removeLayer(layer);if(layer._r72Renderer)map.removeLayer(layer._r72Renderer);}tools.replaceWith(baseControls);bar.remove();sheet.remove();close.remove();dialog.remove();grid.classList.remove('r71-sheet-open');document.body.classList.remove('r71-housing','r71-panorama');if(active?.map===map)active=null;}
  function style(u){const m=u.metrics[themeId],outside=!inScope.has(u.id),missing=m.value==null;return {fill:!outside,fillColor:H.color(m.value,themeId),fillOpacity:1,color:selected===u.id?'#153b50':outside?'#c3cccf':missing?'#718694':'#596e78',weight:selected===u.id?2.6:outside?.3:.45,dashArray:missing&&!outside?'3 3':null,r71Missing:missing&&!outside,r75MissingKind:m.status==="suppression"?"suppressed":"missing",r71Outside:outside};}

  function select(id){if(!byId[id]||!inScope.has(id))return;selected=id;layer.setStyle(f=>style(byId[f.properties.id]));openSheet();detail();map.r72Labels?.schedule();$('searchResults').innerHTML='';}
  function bars(section){if(!section)return '';return '<details open><summary>'+esc(section.label)+'</summary><p>'+esc(section.universe||'')+'</p>'+section.cells.map(c=>'<div class="r71-bar-row"><div><span>'+esc(c.label)+'</span><b>'+(C.finite(c.value)?F(c.value,2)+'%':esc(status(c.status)))+'</b></div><div class="r71-bar" data-family="'+(themeId==='joint'?'red':'blue')+'"><span style="width:'+(C.finite(c.value)?Math.min(100,c.value):0)+'%"></span></div><small>'+F(c.quantity??c.num,0)+' domicílios'+(scale==='ap'?' estimados · '+F(c.cases,0)+' casos amostrais':'')+'</small></div>').join('')+'<p>Denominador: '+F(section.den??section.cells[0]?.den,scale==='ap'?2:0)+' domicílios'+(scale==='ap'?' estimados.':'. Composição '+(section.complete?'completa.':'parcial; supressões preservadas.'))+'</p></details>';}
  function detail(){if(!selected){$('detail').innerHTML='<p>Busque o código ou clique numa unidade do recorte para abrir seus valores e fontes.</p>';return;}
   const u=byId[selected],m=u.metrics[themeId],sample=scale==='ap';let h='<span class="r71-badge">'+(sample?'AP INTEIRA · AMOSTRA · SEM IC':'AGREGADOS DO UNIVERSO')+'</span><h2>'+esc(u.name)+'</h2><p>'+esc(u.reference||u.id)+' · '+esc(cfg.cities[city].name)+' · Censo 2022</p><strong class="r71-value">'+F(m.value,2)+(themeId==='residents'||m.value==null?'':'%')+'</strong><p>'+esc(theme.unit)+'<br>'+esc(status(m.status))+'</p><p><b>Universo:</b> '+esc(m.universe||theme.universe)+'.</p><div class="r71-detail-values"><div><b>'+F(m.den,sample?2:0)+'</b><span>Denominador '+(sample?'ponderado':'publicado')+' · domicílios</span></div>';
   if(themeId!=='residents')h+='<div><b>'+F(m.quantity??m.num,0)+'</b><span>Domicílios '+(sample?'estimados':'contados')+' na condição · '+esc(status(m.quantity_status||m.status))+'</span></div>';h+='</div>';
   h+='<details class="r76-household-method"><summary>Fonte e metodologia</summary><p><b>Definição e fórmula:</b> '+esc(theme.rule)+'</p>';if(themeId==='residents')h+='<p>Média oficial em DPO. Não indica automaticamente superlotação. Valores a partir de 5 usam a última cor; o valor real acima é preservado.</p>'+bars(u.composition);
   if(sample){h+='<p>'+F(m.n_eligible,0)+' domicílios amostrais elegíveis; '+F(m.cases,0)+' casos na condição. Ausentes/inválidos: '+F(m.invalid,0)+'. Peso D0111 uma vez por domicílio.</p><p class="r71-note">'+(map._r73Clip?(map._r73Clip.units.ap.contained.includes(u.id)?'Geometria de exibição inteiramente contida no recorte':'Geometria de exibição cruza o limite do recorte'):'AP inteira; contexto municipal')+'. A estimativa representa a AP inteira; não há total do território selecionado.</p><p>Moradores de 0–17 anos e ambas as respostas válidas; condições simultâneas no mesmo domicílio. Não é percentual de crianças.</p>'+bars(u.details?.joint);}
   if(map._r73Clip)h+='<p class="r73-clip-explanation">'+esc(ACU_R73_DISPLAY.notice(map,scale))+' O desenho é limitado ao território selecionado. Valor, denominador, fonte e situação se referem à unidade original completa, inclusive sua parte externa. Não há estimativa do fragmento nem rateio por área.</p>';
   const ids=[...new Set([m.source_id,...(m.supporting_source_ids||[]),...(m.quantity_source_ids||[]),u.location_source_id,...(themeId==='residents'?[u.composition?.source_id]:[])].filter(Boolean))];h+='<button id="r71-zoom-unit" type="button">Enquadrar unidade</button><p><b>Fontes:</b><br>'+ids.map(sourceLink).join('<br>')+'</p></details>';$('detail').innerHTML=h;$('zoom-unit').onclick=()=>context.withNavigation(()=>map.fitBounds(geometries[selected].properties.bounds,{padding:[24,24],animate:false}));
  }
  function renderLegend(){const a=H.knots(themeId);legend.hidden=false;legend.classList.add('r71-household-legend');legend.innerHTML='<div class="r71-legend-main"><strong>'+esc(themeId==='residents'?'Pessoas por DPO':scale==='ap'?'% dos domicílios elegíveis com moradores de 0–17 anos':'% dos DPPO na condição')+'</strong><canvas id="r71-gradient" width="512" height="10" aria-label="Escala sequencial de magnitude"></canvas><div class="r71-ticks">'+a.map((v,i)=>'<span>'+(themeId==='residents'&&i===0?'≤ ':themeId==='residents'&&i===4?'≥ ':'')+F(v,themeId==='residents'?1:scale==='ap'?2:0)+'</span>').join('')+'</div></div><div class="r71-keys"><span><i class="r75-missing-key"></i>Sem dado / não aplicável</span><span><i class="r75-suppressed-key"></i>Suprimido</span><span><i class="r71-outside-key"></i>Fora do recorte</span><small>'+(themeId==='residents'?'Maior média → · intervalos não uniformes · não mede superlotação.':'Escala fixa · maior privação → · zero válido recebe o tom mais claro.')+'</small></div>';H.paint($('gradient'),themeId);}
  function about(){dialog.querySelector('.r71-about-body').innerHTML='<h3>'+esc(theme.title)+'</h3><p>'+esc(theme.rule)+'</p><p><b>Universo:</b> '+esc(theme.universe)+'.</p><p><b>Cobertura:</b> '+esc($('coverage').textContent)+'. '+(scale==='ap'&&context.geography.id==='DAICO_ACU_OPERATIONAL_2022'?'Sete APs da seleção estatística validada, sem ampliação do cruzamento. Contenção e interseção geométricas foram reconferidas para a apresentação R73; não equivalem a uma nova seleção estatística.':'No município, são todas as unidades da base; nos demais recortes, unidades inteiras com interseção de área positiva com o limite adotado.')+' Não é cobertura em área nem contagem de domicílios do território. Ausência, supressão e denominador zero mantêm situações próprias.</p><p><b>Cores:</b> azul para média de moradores e vermelho para as privações WASH; maior valor recebe tom mais escuro da mesma família, sem classes de risco. Pontos absolutos comuns às cinco cidades: '+H.knots(themeId).map(v=>F(v,2)).join(' / ')+'. '+(themeId==='residents'?'Interpolação por trechos, intervalos não uniformes. Saturação até 1 e a partir de 5 pessoas por DPO; extremos não foram excluídos.':'Interpolação contínua; limites fixos. Valores acima do último limite usam a cor mais escura; o valor real permanece na ficha.')+'</p><p>Moradores: DPO, permanentes e improvisados. Composição e WASH: DPPO. Não comparar esses universos como equivalentes.</p><p>'+(scale==='ap'?'Estimativas da amostra por AP inteira, peso D0111 aplicado uma vez por domicílio elegível. Sem intervalo de confiança; APs cruzadas não fornecem total do território selecionado.':'Setores censitários completos e agregados do universo, sem imputação ou rateio territorial.')+'</p><p><b>Contexto cartográfico:</b> Mapa de ruas online: <a href="https://openfreemap.org/" target="_blank" rel="noopener">OpenFreeMap</a>, © OpenMapTiles e contribuidores OpenStreetMap. Depende de conexão e de WebGL; rótulos e vias ficam acima dos indicadores, sem interceptar cliques. Na indisponibilidade, base regional de apoio IBGE BC250 2023, 1:250.000, de menor detalhe. Nenhuma característica domiciliar é atribuída a endereço.</p><p>'+cfg.cities[city].indicators[themeId].source_ids.map(sourceLink).join('<br>')+'</p>';dialog.showModal();}
  active={map,destroy,refreshLegacy:legacy,get isHousing(){return isHousing;},exportRows:()=>units.filter(u=>inScope.has(u.id)).map(u=>{const m=u.metrics[themeId];return {city:cfg.cities[city].name,geography_id:u.id,geography:u.name,geographic_level:scale,indicator_id:'housing:'+themeId,indicator:theme.title,selected_measure:themeId==='residents'?'mean':'percentage',selected_value:m.value??'',count:'',percentage:themeId==='residents'?'':m.value??'',rate:'',availability:m.status,unit:theme.unit,period:'2022',source:source[m.source_id]?.institution||m.source_id,source_id:m.source_id,lineage_id:m.lineage_id,numerator:m.num??"",denominator:m.den??"",sample_households:m.n_eligible??"",sample_cases:m.cases??"",universe:m.universe||theme.universe,formula:theme.rule,estimate_scope:scale==="ap"?"AP inteira; não corresponde ao fragmento visual":"Setor inteiro",precision:scale==="ap"?"Sem IC; desenho de variância não materializado":"Contagem do universo; supressões preservadas"};}),renderLegend,update:next=>prepare(next).then(p=>{if(!disposed)commit(next,p);}),commit,snapshot:()=>({ready,city,theme:themeId,legacyTheme:context.theme,indicator:context.indicator,scale,geography:context.geography.id,selected,household:isHousing,available:isHousing?units.length>0:false,scopeUnits:inScope.size,visibleLayers:polygons.size,knots:isHousing?H.knots(themeId):null,sheetOpen:grid.classList.contains('r71-sheet-open')}),qa:()=>({data:D,geometry:G,layers:polygons,selected:byId[selected],scope,scopeIds:[...inScope],theme,contextSources:window['ACU_R71_CONTEXT_'+city]})};

  function publishLabels(){
   if(!isHousing)return;
   map.r72Labels?.set([...polygons].filter(([id])=>inScope.has(id)).map(([id,l])=>{const u=byId[id],m=u.metrics[themeId];return {id,layer:l,feature:ACU_R73_DISPLAY.feature(map,l.feature,id,scale),name:u.name,value:m.value,available:m.value!=null,status:m.status,unit:theme.unit,mean:themeId==='residents',indicator:'housing:'+themeId,dense:true};}).filter(e=>e.feature));
  }
  function commit(next,prepared){
   const oldScale=scale,oldHousing=isHousing,oldLayer=layer,oldSelected=selected;
   context=next;isHousing=next.theme==='R71_HOUSEHOLDS';themeId=String(next.indicator||'').replace('housing:','');scale=themeId==='joint'?'ap':'setor';theme=cfg.themes[themeId];
   document.body.classList.toggle('r71-housing',isHousing);sheet.hidden=!isHousing;$('find').textContent=isHousing?'Buscar unidade':'Território em números';$('find').disabled=false;
   if(!isHousing){if(layer){map.removeLayer(layer);if(layer._r72Renderer)map.removeLayer(layer._r72Renderer);}layer=null;polygons=new Map();selected=null;legend.classList.remove('r71-household-legend');legacy();$('about').onclick=()=>context.openMethod();ready=true;return;}
   [D,G]=prepared;source=Object.fromEntries([...D.sources,...cfg.sources].map(s=>[s.source_id,s]));units=D.units[scale]||[];byId=Object.fromEntries(units.map(u=>[u.id,u]));geometries=Object.fromEntries((G.units[scale]||[]).map(f=>[f.properties.id,f]));scope=coverageData?.[context.geography.id];inScope=new Set(scope?.units[scale]||[]);
   selected=oldHousing&&oldScale===scale&&byId[oldSelected]&&inScope.has(oldSelected)?oldSelected:null;
   $('measure').textContent=(themeId==='residents'?'Pessoas por domicílio ocupado':scale==='ap'?'DPPO com moradores de 0–17 anos (%)':'Domicílios na condição (%)')+' · '+(scale==='ap'?'AP':'Setores')+' · 2022';
   const valid=units.filter(u=>inScope.has(u.id)&&u.metrics[themeId]?.value!=null).length;
   $('coverage').textContent=valid.toLocaleString('pt-BR')+'/'+inScope.size.toLocaleString('pt-BR')+' '+(scale==='ap'?'APs inteiras com valor · sem total do território':'setores com valor')+' · '+(context.geography.name||context.geography.id);
   if(map._r73Clip)$('coverage').textContent+=' · '+ACU_R73_DISPLAY.notice(map,scale);
   if(urbanFrame)$('coverage').textContent+=' · enquadramento urbano; cobertura municipal.';
   if(!units.length){ACU_R72R1.setArea(map,[]);if(oldLayer){map.removeLayer(oldLayer);if(oldLayer._r72Renderer)map.removeLayer(oldLayer._r72Renderer);}layer=null;polygons=new Map();legend.hidden=true;$('coverage').textContent='Base desse cruzamento por AP não validada nesta cidade.';$('find').disabled=true;}
   else if(oldHousing&&oldScale===scale&&oldLayer){layer=oldLayer;ACU_R72.animate(layer,f=>style(byId[f.properties.id]));}
   else{
    if(!map.getPane('r71Indicator'))map.createPane('r71Indicator');map.getPane('r71Indicator').style.zIndex=420;
    const renderer=new ACU_R73_DISPLAY.Renderer({pane:'r71Indicator',padding:.2}),nextPolygons=new Map(),nextLayer=L.geoJSON(G.units[scale],{pane:'r71Indicator',renderer,style:f=>style(byId[f.properties.id]),onEachFeature:(f,l)=>{const id=f.properties.id;ACU_R73_DISPLAY.guard(l,map);nextPolygons.set(id,l);
     l.bindTooltip(()=>{const u=byId[id],m=u.metrics[themeId];return '<b>'+esc(u.name)+'</b><br>'+ACU_R72.format(m.value,{unit:theme.unit,mean:themeId==='residents',detail:true,precision:themeId==='residents'?1:2})+'<br>'+esc(theme.unit)+'<br>'+esc(status(m.status));},{sticky:true,opacity:1});
     l.on('click',e=>{if(e.originalEvent)L.DomEvent.stopPropagation(e.originalEvent);select(id);});
    }});
    nextLayer._r72Renderer=renderer;nextLayer.addTo(map);layer=nextLayer;polygons=nextPolygons;if(oldLayer){map.removeLayer(oldLayer);if(oldLayer._r72Renderer)map.removeLayer(oldLayer._r72Renderer);}
   }
   if(units.length)renderLegend();detail();$('about').onclick=about;
   const fold=x=>String(x??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
   $('search').oninput=e=>{const q=fold(e.target.value.trim());$('searchResults').innerHTML=q.length<2?'':units.filter(u=>inScope.has(u.id)&&fold(u.id+' '+u.name+' '+u.reference).includes(q)).slice(0,8).map(u=>'<button data-r71-unit="'+u.id+'" type="button">'+esc(u.name)+'<small>'+esc(u.reference||'')+'</small></button>').join('');};
   $('searchResults').onclick=e=>{const b=e.target.closest('[data-r71-unit]');if(b){select(b.dataset.r71Unit);context.withNavigation(()=>map.fitBounds(geometries[selected].properties.bounds,{padding:[24,24],animate:false}));}};
   ACU_R72R1.setArea(map,ACU_R73_DISPLAY.area(map)||[...polygons].filter(([id])=>inScope.has(id)).map(([,l])=>l.feature));
   publishLabels();ready=true;
  }
  if(isHousing){prepare(context).then(p=>{if(!disposed){commit(context,p);context.refreshBase();}}).catch(e=>{if(!disposed){$('measure').textContent=e.message;bar.dataset.error=e.message;}});}
  else{ready=true;context.refreshLabels?.();}

 }
 window.ACU_R71_PANORAMA={mount,prepare,refreshLegend:()=>active?.renderLegend?.(),exportRows:()=>active?.exportRows?.()||[],commit:(c,p)=>active?.map===c.map?active.commit(c,p):mount(c),beforeRender:ctx=>{stop();document.body.classList.toggle('r71-panorama',ctx?.module==='panorama');document.body.classList.toggle('r71-housing',ctx?.module==='panorama'&&document.querySelector('#theme-select')?.value==='R71_HOUSEHOLDS');},onCityChange:()=>{stop();lastScope=null;pendingLegacy=false;},reset:()=>{stop();lastScope=null;},isActive:()=>!!active?.isHousing,snapshot:()=>active?.snapshot(),qa:()=>active?.qa(),getMap:()=>active?.map,refreshLegacy:()=>active?.refreshLegacy(),requestLegacySheet:()=>{pendingLegacy=true;}};
})();
