/* Presentation only. No source values, geographies, denominators or cuts change. */
window.ACU_R75=(()=>{
 const palettes={blue:['#EFF3FF','#BDD7E7','#6BAED6','#3182BD','#08519C'],red:['#FEE5D9','#FCAE91','#FB6A4A','#DE2D26','#A50F15']};
 function profile(city,id){const p=window.ACU_R75_POLICY_DATA?.[city]?.[id]||{direction:'descriptive',family:'blue',reason:'Sem definição normativa validada.'};return {...p,palette:palettes[p.family],semantic_direction:{adverse:'HIGHER_IS_WORSE',favorable:'HIGHER_IS_BETTER',descriptive:'NO_NORMATIVE_DIRECTION'}[p.direction],normative_use_allowed:false,palette_strategy:p.family==='red'?'SEQUENTIAL_RED':'SEQUENTIAL_BLUE'};}
 function number(x,digits=1){if(x===null||x===undefined||x===''||!Number.isFinite(Number(x)))return '—';const v=Number(x);let d=digits;if(v!==0&&Math.abs(v)<.5*10**-d)d=Math.min(12,Math.max(d,Math.ceil(-Math.log10(Math.abs(v)))+1));return v.toLocaleString('pt-BR',{minimumFractionDigits:digits,maximumFractionDigits:d});}
 function format(x,unit=''){if(x===null||x===undefined||x===''||!Number.isFinite(Number(x)))return 'N/D';const u=String(unit).toLowerCase();if(u.includes('%')||u==='percent')return number(x,1)+'%';if(/moradores.*domic|pessoas.*domic|média|media|mean/.test(u))return number(x,2);if(/r\$|brl|reais|km|variância|variancia/.test(u))return number(x,2);if(/índice|indice|index/.test(u))return number(x,1);return number(x,0);}
 function boundaries(bounds){const cuts=[...new Set(bounds.flatMap(b=>[b.min,b.max]))].sort((a,b)=>a-b);let digits=0;while(digits<12&&new Set(cuts.map(v=>number(v,digits))).size<cuts.length)digits++;return bounds.map((b,i)=>b.min===b.max?'= '+number(b.min,digits):(i?' > ':'≥ ')+number(b.min,digits)+' a ≤ '+number(b.max,digits));}
 const reading=p=>p.direction==='adverse'?'Maior privação/ocorrência →':p.direction==='favorable'?'Maior cobertura/resultado →':'Maior quantidade/proporção/média →';
 function metadata(v){if(v===null||v===undefined||v===''||/when_available|canonical_numerator|canonical_denominator/.test(String(v)))return 'Não documentado na base; não inferido.';const labels={BELEM_IBGE_DISTRICT:'Distrito administrativo de Belém',IBGE_DISTRICT:'Distrito administrativo',IBGE_NEIGHBORHOOD:'Bairro oficial',MANAUS_NEIGHBORHOOD:'Bairro oficial de Manaus',SP_DISTRICT:'Distrito administrativo',SP_SUBPREFECTURE:'Subprefeitura',RJ_ADMINISTRATIVE_REGION:'Região Administrativa',RJ_NEIGHBORHOOD:'Bairro oficial',RJ_PLANNING_AREA:'Área de Planejamento',AGENDA_CITY_TERRITORY:'Território Agenda Cidade UNICEF',MUNICIPALITY:'Município',N_A:'Não aplicável','N/A':'Não aplicável','N/D':'Não documentado na base'};return String(v).replace(/[A-Z][A-Z0-9]+(?:_[A-Z0-9]+)+/g,s=>labels[s]||'Referência técnica no registro de rastreabilidade');}
 return {palettes,profile,number,format,boundaries,reading,metadata};
})();
